### ISSUE TITLE
Some gpupdate errors

### ISSUE THREAD

**Issue by xluxeq** [simeononsecurity/Standalone-Windows-STIG-Script#3]
**Describe the bug**
Varying errors on gpupdate /force

**To Reproduce**
1. Apply STIG
2. Reboot
3. run gpupdate /force in command prompt
4. review errors

**Expected behavior**
No errors

**Screenshots**
Updating policy...

Computer Policy update has completed successfully.

The following warnings were encountered during computer policy processing:

Windows failed to apply the Group Policy Registry settings. Group Policy Registry settings might have its own log file. Please click on the "More information" link.
Windows failed to apply the Software Installation settings. Software Installation settings might have its own log file. Please click on the "More information" link.
Windows failed to apply the {FC491EF1-C4AA-4CE1-B329-414B101DB823} settings. {FC491EF1-C4AA-4CE1-B329-414B101DB823} settings might have its own log file. Please click on the "More information" link.
User Policy update has completed successfully.

The following warnings were encountered during user policy processing:

Windows failed to apply the Group Policy Registry settings. Group Policy Registry settings might have its own log file. Please click on the "More information" link.

For more detailed information, review the event log or run GPRESULT /H GPReport.html from the command line to access information about Group Policy results.

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Version 22621.1778

**Comment by simeononsecurity** [comment]
We appreciate the notification.
Seems to be related to https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/issues/58
We're still working on it.
