### ISSUE TITLE
Remove coma on param

### ISSUE THREAD

**Issue by patriotdoge** [simeononsecurity/Standalone-Windows-STIG-Script#4]
**Describe the bug**
Remove coma at the end of the line 36 [.... [bool]$horizon = $true**,** ]

**To Reproduce**
Run the script and the error on that line (36) prevents it from running.

**Comment by simeononsecurity** [comment]
https://github.com/simeononsecurity/Standalone-Windows-STIG-Script/commit/efa8764efcca2d3a921600d411a9d4b96da32145
Thanks for your submission!
