### ISSUE TITLE
Error with windows update

### ISSUE THREAD

**Issue by Nexium57** [simeononsecurity/Standalone-Windows-STIG-Script#7]
Hello,

After running the script, Windows Update can no longer search for Windows updates, an error appears.
Is there a way to resolve this ?

Thanks in advance.

![Capture](https://github.com/simeononsecurity/Standalone-Windows-STIG-Script/assets/158066343/6e41b2c1-4698-4f1d-ab2b-31531f39af11)

**Comment by simeononsecurity** [comment]
@Nexium57 what version of windows are you on Home, Pro, Enterprise? What version of the install did you do and with what options?

**Comment by Nexium57** [comment]
Hello, this is a Windows Home version, is a version 22H2

**Comment by simeononsecurity** [comment]
> Hello, this is a Windows Home version, is a version 22H2

Someone didn't read the [requirements](https://github.com/simeononsecurity/Standalone-Windows-STIG-Script#requirements)....
Home editions are not supported on this script.  Please take care to read the readme before running random scripts on the internet.

Please read the following wiki article explaining how to reverse the changes. It is for a different script, but still applies here.
https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat/wiki/How-to-Reverse-the-Changes-performed-in-Windows%E2%80%90Optimize%E2%80%90Harden%E2%80%90Debloat
